# Generated by Django 5.1.5 on 2025-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beb", "0011_links_descrisione"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="links",
            name="descrisione",
        ),
        migrations.AlterField(
            model_name="links",
            name="descrizione",
            field=models.CharField(default=" ", max_length=512),
        ),
    ]
